### ISSUE TITLE
Fail to decompress the dataset gzip files

### ISSUE THREAD

**Issue by sndnyang** [AlirezaJavadian/Syllabus-to-ONET#1]
Dear Authors

 I  really appreciate your excellent work! It's great to open-source the dataset.

However, I encountered the problem extracting from the dataset file after I download https://figshare.com/articles/dataset/A_national_longitudinal_dataset_of_skills_taught_in_U_S_higher_education_curricula/25632429

![image](https://github.com/AlirezaJavadian/Syllabus-to-ONET/assets/2310591/468b3a8f-8998-48db-9429-667b02af7f84)

I got the gzip files.  then  I tried 7-zip(windows) and gunzip(ubuntu), they failed.  I can't figure out the solution. 
```
gunzip -d ./abilities_scores.gzip
gzip: ./abilities_scores.gzip: unknown suffix -- ignored
```
Can you check it?  It would be a great help if you could do me a favor.

**Comment by AlirezaJavadian** [comment]
Hello,

Thanks for reaching out.
You may want to try load the gzip files using Python. Please see an example below.


```
import pandas as pd

file_path= './abilities_scores.gzip'
df= pd.read_csv(file_path, compression='gzip')
```

If you are interested in potential usages of the dataset, please feel free to read our pre-print:
https://arxiv.org/abs/2404.13163

Please let me know if you have any questions.

Best,
Alireza

**Comment by sndnyang** [comment]
so nice!!!! Thank you so much!
